### ISSUE TITLE
NullPointerException in RightClickEvent.onBlockPlace

### ISSUE THREAD

**Issue by gxam** [Beyond-Reality/BeyondRealityCore#4]
Using 2.1.8 of the pack.  Right clicking on things is crashing me.  I've right clicked with a steel sword, a GT wrench and a couple other random things on a vanilla chest, a GT basic bender and a couple of other things.

I suspect `GameRegistry.findUniqueIdentifierFor` is returning nil.

```
java.lang.NullPointerException: Unexpected error
	at com.mcbeyondreality.beyondrealitycore.event.RightClickEvent.onBlockPlace(RightClickEvent.java:62)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_132_RightClickEvent_onBlockPlace_PlayerInteractEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:91)
```

**Comment by Dominance** [comment]
Pretty sure this was fixed a long time ago sorry just never caught it.
