### ISSUE TITLE
NullPointerException at com.mcbeyondreality.beyondrealitycore.handlers.GuiHandler.addCustomServers(GuiHandler.java:116)

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityCore#8]
Getting this client [crash report](https://gist.github.com/leagris/7a479df707d7b416762f04c96092a375)
Except:
```Java
java.lang.NullPointerException: Initializing game
	at com.mcbeyondreality.beyondrealitycore.handlers.GuiHandler.addCustomServers(GuiHandler.java:116)
	at com.mcbeyondreality.beyondrealitycore.BeyondRealityCore.preInit(BeyondRealityCore.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
…
```

Using [this version of beyondrealitycoreServers.xml](https://github.com/Beyond-Reality/BeyondRealityModPack/blob/a490b6f87bf3f09007e5d7492b972daec9a5b282/BR1710/config/BeyondRealityCore/beyondrealitycoreServers.xml)

**Comment by leagris** [comment]
Needed lowercase tags as there are no safeguards here:
https://github.com/Beyond-Reality/BeyondRealityCore/blob/master/src/main/java/com/mcbeyondreality/beyondrealitycore/handlers/GuiHandler.java#L116

Fixed in: https://github.com/Beyond-Reality/BeyondRealityModPack/commit/efc5f9c06ab62c8528d462b68e00880f58fe12f1
